### ISSUE TITLE
Compatible with current RN?

### ISSUE THREAD

**Issue by tgoldenberg** [rhaker/react-native-play-audio-ios#1]
Hi, I did `npm install react-native-play-audio-ios --save` on a React Native project that was rendering fine, and just installing through off the project. Is this still compatible with latest RN? Chrome gives me the error `Failed to print error:  Requiring module "ExceptionsManager" which threw an exception`. Any suggestions? Thanks!

**Comment by rhaker** [comment]
I just tried it successfully with v0.12.0.  Here's what I suggest:

1) Try a "hello world" version with just a blank project and the module to see if that works
-- do a react-native init cleanTest
-- cd into cleanTest
-- npm install react-native-play-audio-ios
-- open up Xcode by clicking the cleanTest .proj file
-- add the audio module into the library folder and make sure you add the library under Build Phases
-- Copy the code from example.ios.js in the github repo into the index.os.js (renaming testComp to cleanTest)
-- Do a clean and build inside Xcode
-- Run the app in the simulator and when it loads press the Play text.
-- In Xcode (not chrome), you should see a console.log message about the audio file not being available (because it doesn't exist)
-- If you get the message in Xcode, then there's probably a different area of your code that is problematic

2) If #1 doesn't work, there is another module named react-native-audio by jsierles that you can try. You may have better luck with that.

I'm closing this issue. Respond and I'll try to help if I can.
