### ISSUE TITLE
onProgress callback, other playback controls similar to react-native-video

### ISSUE THREAD

**Issue by kanenathan213** [rhaker/react-native-play-audio-ios#5]
I'd love to see the API evolve to be closer to the `<react-native-video>` project, so that it's an `<Audio>` component whose props can be callbacks that enable things like progress, etc.

Happy to start submitting PR's to take it in that direction.

**Comment by rhaker** [comment]
Hi Nathan. Thanks for checking out this module. 

I completely agree that most of these components can be improved with added functionality. I had originally just built this module for a simple way to play audio that I recorded (via my record-audio component). Since then, people have asked for things like volume control and additional features. And it's on my todo list, just at the bottom. And new modules I want to code keep being prioritized to the top of the list (plus I'm in the final stages of launching my first React Native app).

A few thoughts:

1) If you want to add some functionality, free feel. I'll merge whatever you do, if you think it's an improvement. Also, feel free to fork the code.

2) There's a react-native-audio module by Josh Sierles that I first looked at before building this module. At the time, it only had limited options (e.g. only played .caf files, etc). I'm not sure if it's progressed, but you might also want to coordinate with Josh.

All the best.
